"""empty message

Revision ID: 2382b9c8750d
Revises: 
Create Date: 2023-09-12 15:31:29.489710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2382b9c8750d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address_one', sa.String(length=100), nullable=False),
    sa.Column('address_two', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=30), nullable=False),
    sa.Column('zip_code', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conductor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(length=75), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('token', sa.String(length=32), nullable=True),
    sa.Column('token_expiration', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('conductor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conductor_token'), ['token'], unique=True)

    op.create_table('service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tune',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tune_name', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('website', sa.String(length=75), nullable=False),
    sa.Column('conductor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['conductor_id'], ['conductor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('website')
    )
    op.create_table('choir',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hymn',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hymnal_number', sa.String(length=5), nullable=False),
    sa.Column('first_line', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('author', sa.String(length=50), nullable=False),
    sa.Column('meter', sa.String(length=50), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('pub_date', sa.String(length=4), nullable=False),
    sa.Column('copyright', sa.String(length=200), nullable=True),
    sa.Column('tune_name', sa.String(length=20), nullable=False),
    sa.Column('arranger', sa.String(length=50), nullable=True),
    sa.Column('key', sa.String(length=5), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('audio_rec', sa.String(length=200), nullable=True),
    sa.Column('tune_id', sa.Integer(), nullable=True),
    sa.Column('choir_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['choir_id'], ['choir.id'], ),
    sa.ForeignKeyConstraint(['tune_id'], ['tune.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hymn_sunday',
    sa.Column('hymn_id', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hymn_id'], ['hymn.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], )
    )
    op.create_table('hymn_topic',
    sa.Column('hymn_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hymn_id'], ['hymn.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hymn_topic')
    op.drop_table('hymn_sunday')
    op.drop_table('hymn')
    op.drop_table('choir')
    op.drop_table('organization')
    op.drop_table('tune')
    op.drop_table('topic')
    op.drop_table('service')
    with op.batch_alter_table('conductor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conductor_token'))

    op.drop_table('conductor')
    op.drop_table('address')
    # ### end Alembic commands ###
