"""empty message

Revision ID: 8b391898c358
Revises: 9ed20290242b
Create Date: 2023-09-21 11:45:12.094793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b391898c358'
down_revision = '9ed20290242b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hymn', schema=None) as batch_op:
        batch_op.add_column(sa.Column('composer', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hymn', schema=None) as batch_op:
        batch_op.drop_column('composer')

    # ### end Alembic commands ###