"""empty message

Revision ID: 9ed20290242b
Revises: bfa22bd926f5
Create Date: 2023-09-15 02:10:00.903971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ed20290242b'
down_revision = 'bfa22bd926f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hymn', schema=None) as batch_op:
        batch_op.alter_column('first_line',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('author',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('meter',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('language',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('pub_date',
               existing_type=sa.VARCHAR(length=4),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hymn', schema=None) as batch_op:
        batch_op.alter_column('pub_date',
               existing_type=sa.VARCHAR(length=4),
               nullable=False)
        batch_op.alter_column('language',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('meter',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('author',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('first_line',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
