"""empty message

Revision ID: bfa22bd926f5
Revises: d94e4806392c
Create Date: 2023-09-13 10:41:13.268639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfa22bd926f5'
down_revision = 'd94e4806392c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hymn_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('service_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('program_service_id_fkey', 'service', ['service_id'], ['id'])
        batch_op.create_foreign_key('program_hymn_id_fkey', 'hymn', ['hymn_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('program', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('service_id')
        batch_op.drop_column('hymn_id')

    # ### end Alembic commands ###
