"""empty message

Revision ID: d94e4806392c
Revises: 1c3940b4d0ef
Create Date: 2023-09-13 10:36:16.655471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd94e4806392c'
down_revision = '1c3940b4d0ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('program',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hymn_id', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('conductor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hymn_id'], ['hymn.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.ForeignKeyConstraint(['conductor_id'], ['conductor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('hymn_sunday')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hymn_sunday',
    sa.Column('hymn_id', sa.INTEGER(), nullable=True),
    sa.Column('service_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['hymn_id'], ['hymn.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], )
    )
    op.drop_table('program')
    # ### end Alembic commands ###
